name: Deploy to Firebase Hosting on merge
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - run: echo 🦄🦄
